export const INITIALIZE_GAME = 'INITIALIZE_GAME';
export const SHUFFLE_DECK = 'SHUFFLE_DECK';
export const HANDLE_SELECTED_CARD = 'HANDLE_SELECTED_CARD';
export const MOVE_TO_NEXT_ROUND = 'MOVE_TO_NEXT_ROUND';
export const CALCULATE_SCORE = 'CALCULATE_SCORE';
export const EVALUATE_WINNER = 'EVALUATE_WINNER';
export const GAME_OVER = 'GAME_OVER'